services:

  rating-command-service:
    build: ./rating-command-service
    container_name: rating-command-service
    ports:
      - 8080:8080
    restart: no
    volumes:
      - ./rating-command-service:/rating-command-service
    networks:
      - dev

networks:

  dev:
    driver: bridge
